name: Apply ULTIMATE+ (direct, PR-killer)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: Waar landen de wijzigingen?
        type: choice
        options: [main, branch]
        default: branch
      branch:
        description: Branchnaam (bij mode=branch)
        required: false
        default: auto/apply-ultimate-plus
      release:
        description: Maak tag + GitHub Release met artifacts (alleen bij mode=main)
        type: boolean
        default: false
      tag:
        description: Optionele tag (bv. v1.0.0). Leeg = datumtag.
        required: false
        default: ""

permissions:
  contents: write
  issues: write

concurrency:
  group: apply-ultimate-direct
  cancel-in-progress: true

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # 1) Verwijder ALLE workflows die PR's proberen te maken (bron van de fout)
      - name: Purge PR-based workflows
        run: |
          set -e
          mkdir -p .github/workflows
          # lijst van bekende apply-workflows die PR maken
          rm -f .github/workflows/apply-plus-update.yml || true
          # alles wat create-pull-request aanroept uitschakelen
          for f in .github/workflows/*.yml; do
            if [ -f "$f" ] && grep -q "create-pull-request" "$f"; then
              echo "Disabling PR workflow: $f"
              mv "$f" "${f}.disabled"
            fi
          done
          # commit directe wijziging zodat ze niet opnieuw aftrappen
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: purge PR-based workflows (policy-safe)"
            git push origin HEAD:main || true
          fi

      # 2) Schrijf ULTIMATE+ bestanden (geen PR)
      - name: Write ULTIMATE+ files
        run: |
          python - <<'PY'
          import pathlib, textwrap
          root = pathlib.Path(".")
          (root / "utils").mkdir(parents=True, exist_ok=True)
          (root / "pages").mkdir(parents=True, exist_ok=True)
          (root / ".github" / "workflows" / "scripts").mkdir(parents=True, exist_ok=True)

          (root / "utils" / "costing.py").write_text(textwrap.dedent("""\
          def machine_cost_per_hour(capex_eur, lifetime_yrs, utilization_pct, maintenance_pct, energy_eur_per_kwh, kwh_per_hour):
              hrs_per_year = 2000.0
              depreciation = capex_eur / (lifetime_yrs * hrs_per_year)
              maintenance  = (capex_eur * maintenance_pct) / (lifetime_yrs * hrs_per_year)
              energy = energy_eur_per_kwh * kwh_per_hour
              return (depreciation + maintenance + energy) / max(utilization_pct, 0.01)

          def labor_cost_per_hour(hourly_rate, overhead_pct, margin_pct):
              return hourly_rate * (1.0 + overhead_pct) * (1.0 + margin_pct)

          def part_cost(material_kg, price_eur_per_kg, process_time_h, machine_rate_eur_h, labor_time_h, labor_rate_eur_h):
              return (material_kg * price_eur_per_kg) + (process_time_h * machine_rate_eur_h) + (labor_time_h * labor_rate_eur_h)

          def apply_scenario(rate, multiplier):
              return rate * multiplier
          """), encoding="utf-8")

          (root / "pages" / "15_BOM_Calculatie_PLUS.py").write_text(textwrap.dedent("""\
          from bootstrap import configure_page, init_state
          from utils.safe import run_safely
          from utils.io import read_csv_safe, SCHEMA_BOM, SCHEMA_MATERIALS, paths
          from utils.costing import part_cost
          import streamlit as st, pandas as pd
          configure_page(); init_state()
          st.title("BOM Calculatie - PLUS")
          P = paths()
          materials = run_safely("Load materials", read_csv_safe, P["materials"], SCHEMA_MATERIALS)
          if materials is None: st.stop()
          up = st.file_uploader("Upload BOM CSV (of gebruik data/bom_template.csv)", type=["csv"])
          if up: bom = run_safely("Read uploaded BOM", pd.read_csv, up)
          else:  bom = run_safely("Read BOM template", read_csv_safe, P["bom"], SCHEMA_BOM)
          if bom is None: st.stop()
          needed = ["material_id","qty","mass_kg","process_route"]
          missing = [c for c in needed if c not in bom.columns]
          if missing: st.error("Ontbrekende BOM kolommen: " + ", ".join(missing)); st.stop()
          view = bom.merge(materials[["material_id","price_eur_per_kg"]], on="material_id", how="left")
          st.sidebar.header("Aannames (demo)")
          lt_per_qty = st.sidebar.number_input("Arbeidstijd per qty (uur)", min_value=0.0, value=0.1, step=0.05)
          mt_per_qty = st.sidebar.number_input("Machinetijd per qty (uur)", min_value=0.0, value=0.05, step=0.05)
          machine_rate = st.sidebar.number_input("Machine rate (EUR/h)", min_value=0.0, value=80.0, step=5.0)
          labor_rate   = st.sidebar.number_input("Labor rate (EUR/h)",   min_value=0.0, value=45.0, step=5.0)
          def calc_row(r):
              mk = (r.get("mass_kg") or 0.0); qty = (r.get("qty") or 0.0); price = (r.get("price_eur_per_kg") or 0.0)
              lt = qty * lt_per_qty; mt = qty * mt_per_qty
              return part_cost(mk, price, mt, machine_rate, lt, labor_rate)
          view["part_cost_eur"] = view.apply(calc_row, axis=1)
          totals = float(view["part_cost_eur"].sum())
          txt = f"Totaal kostprijs (demo): EUR {totals:,.2f}".replace(",", "X").replace(".", ",").replace("X",".")
          st.success(txt)
          st.dataframe(view, use_container_width=True)
          """), encoding="utf-8")

          (root / "pages" / "16_Routing_Kosten_PLUS.py").write_text(textwrap.dedent("""\
          from bootstrap import configure_page, init_state
          from utils.safe import run_safely
          from utils.io import read_csv_safe, SCHEMA_PROCESSES, paths
          from utils.costing import machine_cost_per_hour, labor_cost_per_hour
          import streamlit as st
          configure_page(); init_state()
          st.title("Routing Kosten - PLUS")
          p = paths()["processes"]
          df = run_safely("Load processes", read_csv_safe, p, SCHEMA_PROCESSES)
          if df is None: st.stop()
          st.subheader("Basis tarieven (CSV)")
          st.dataframe(df[["process_id","machine_rate_eur_h","labor_rate_eur_h","overhead_pct","margin_pct"]].fillna(""),
                       use_container_width=True)
          st.sidebar.header("Machine uurkosten (model)")
          capex = st.sidebar.number_input("CAPEX (EUR)", min_value=0.0, value=120000.0, step=5000.0)
          life  = st.sidebar.number_input("Levensduur (jaar)", min_value=1.0, value=7.0, step=0.5)
          util  = st.sidebar.number_input("Bezettingsgraad (0-1)", min_value=0.05, max_value=1.0, value=0.65, step=0.05)
          maint = st.sidebar.number_input("Onderhoud % CAPEX", min_value=0.0, max_value=1.0, value=0.05, step=0.01)
          ekwh  = st.sidebar.number_input("Energie (EUR/kWh)", min_value=0.0, value=0.25, step=0.01)
          kwh   = st.sidebar.number_input("Verbruik (kWh/uur)", min_value=0.0, value=8.0, step=0.5)
          model_rate = machine_cost_per_hour(capex, life, util, maint, ekwh, kwh)
          st.info(f"Model: machine-uurkosten ~ EUR {model_rate:,.2f}".replace(",", "X").replace(".", ",").replace("X","."))
          st.sidebar.header("Arbeid")
          hr = st.sidebar.number_input("Bruto uurloon", min_value=0.0, value=40.0, step=1.0)
          oh = st.sidebar.number_input("Overhead %", min_value=0.0, max_value=1.0, value=0.2, step=0.05)
          mg = st.sidebar.number_input("Marge %",   min_value=0.0, max_value=1.0, value=0.1, step=0.05)
          lrate = labor_cost_per_hour(hr, oh, mg)
          st.info(f"Model: labor-uurkosten ~ EUR {lrate:,.2f}".replace(",", "X").replace(".", ",").replace("X","."))
          """), encoding="utf-8")

          (root / "pages" / "06_ScenarioPlanner_PLUS.py").write_text(textwrap.dedent("""\
          from bootstrap import configure_page, init_state
          from utils.safe import run_safely
          from utils.io import read_csv_safe, SCHEMA_PROCESSES, paths
          import streamlit as st, pandas as pd
          configure_page(); init_state()
          st.title("Scenario Planner - PLUS")
          df = run_safely("Load processes", read_csv_safe, paths()["processes"], SCHEMA_PROCESSES)
          if df is None: st.stop()
          m_mult = st.sidebar.number_input("Machine multiplier", min_value=0.0, value=1.15, step=0.05)
          l_mult = st.sidebar.number_input("Labor multiplier",   min_value=0.0, value=1.05, step=0.05)
          out = df.copy()
          if "machine_rate_eur_h" in out.columns:
              out["machine_rate_eur_h_scn"] = out["machine_rate_eur_h"] * m_mult
          if "labor_rate_eur_h" in out.columns:
              out["labor_rate_eur_h_scn"] = out["labor_rate_eur_h"] * l_mult
          st.subheader("Scenario output")
          st.dataframe(out, use_container_width=True)
          def delta_pct(new, old):
              return ((pd.to_numeric(new, errors="coerce") - pd.to_numeric(old, errors="coerce")) / pd.to_numeric(old, errors="coerce"))*100.0
          if "machine_rate_eur_h" in out.columns and "machine_rate_eur_h_scn" in out.columns:
              out["delta_machine_pct"] = delta_pct(out["machine_rate_eur_h_scn"], out["machine_rate_eur_h"]).round(1)
          if "labor_rate_eur_h" in out.columns and "labor_rate_eur_h_scn" in out.columns:
              out["delta_labor_pct"] = delta_pct(out["labor_rate_eur_h_scn"], out["labor_rate_eur_h"]).round(1)
          """), encoding="utf-8")
          PY

      # 3) Als er iets veranderd is, commit direct (branch of main)
      - name: Detect changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure git
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit to branch (policy-safe)
        if: steps.changes.outputs.changed == 'true' && inputs.mode == 'branch'
        run: |
          git checkout -B "${{ inputs.branch }}"
          git add -A
          git commit -m "chore: apply ULTIMATE+ update (direct, no PR)"
          git push -f -u origin "${{ inputs.branch }}"

      - name: Commit to main (opt-in)
        if: steps.changes.outputs.changed == 'true' && inputs.mode == 'main'
        run: |
          git add -A
          git commit -m "chore: apply ULTIMATE+ update (direct, no PR)"
          git push origin HEAD:main

      # 4) Bouw artifacts en upload (optioneel release op main)
      - name: Setup Python
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Build artifacts
        if: steps.changes.outputs.changed == 'true'
        run: |
          python -m pip install -U pip pandas openpyxl
          python .github/workflows/scripts/build_plus_artifacts.py || true
          ls -la dist || true

      - name: Upload artifacts
        if: steps.changes.outputs.changed == 'true' && hashFiles('dist/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: cost-tool-plus
          path: dist/*
          retention-days: 14

      - name: Tag & push
        if: steps.changes.outputs.changed == 'true' && inputs.mode == 'main' && inputs.release == 'true'
        env:
          TAG: ${{ inputs.tag }}
        run: |
          set -e
          if [ -z "$TAG" ]; then TAG="v$(date -u +%Y.%m.%d-%H%M)"; fi
          git tag "$TAG"
          git push origin "$TAG"
          echo "Created tag $TAG"

      - name: GitHub Release
        if: steps.changes.outputs.changed == 'true' && inputs.mode == 'main' && inputs.release == 'true' && hashFiles('dist/*') != ''
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
